/**
 * Cocktails API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IngredientDto } from './ingredientDto';


export interface CocktailDto { 
    id: string;
    name: string;
    imgSrc?: string;
    ingredients: Array<IngredientDto>;
}

