/**
 * Cocktails API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ingredient } from './ingredient';


export interface CocktailDto { 
    imgSrc?: string;
    id: string;
    name: string;
    ingredients: Array<Ingredient>;
}

