/**
 * Cocktails API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemDto } from './orderItemDto';


export interface CreateOrderDto { 
    orderer: string;
    orderitems: Array<OrderItemDto>;
}

